os: Visual Studio 2017

environment:
  matrix:
    - platform: x64
      target: x86_64-pc-windows-msvc
      qtdir: C:\Qt\5.13.2\msvc2017_64
      sysdirname: SysWOW64

    - platform: x86
      target: i686-pc-windows-msvc
      qtdir: C:\Qt\5.13.2\msvc2017
      sysdirname: system32

cache:
  CGAL-5.1-beta1-Setup.exe -> appveyor.yml

install:
  - if "%PLATFORM%" == "x64"
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%PLATFORM%" == "x86"
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
    
  - cd thirdparty/blosc/c-blosc-1.18.1
  - mkdir build
  - cd build
  - if "%PLATFORM%" == "x64"
    cmake -G "Visual Studio 15 2017" -A %PLATFORM% -D "BUILD_SHARED=OFF" -D "BUILD_TESTS=OFF" -D "BUILD_BENCHMARKS=OFF" ../
  - if "%PLATFORM%" == "x86"
    cmake -G "Visual Studio 15 2017" -D "BUILD_SHARED=OFF" -D "BUILD_TESTS=OFF" -D "BUILD_BENCHMARKS=OFF" ../
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  
  - cd thirdparty/zlib/zlib-1.2.11
  - mkdir build
  - cd build
  - if "%PLATFORM%" == "x64"
    cmake -G "Visual Studio 15 2017" -A %PLATFORM% ../
  - if "%PLATFORM%" == "x86"
    cmake -G "Visual Studio 15 2017" ../
  - cmake --build . --config Release
  - copy %APPVEYOR_BUILD_FOLDER%\thirdparty\zlib\zlib-1.2.11\build\zconf.h %APPVEYOR_BUILD_FOLDER%\thirdparty\zlib\zlib-1.2.11\zconf.h
  - cd %APPVEYOR_BUILD_FOLDER%
  
  - cd thirdparty/openexr/openexr-2.4.1
  - mkdir build
  - cd build
  - if "%PLATFORM%" == "x64"
    cmake -G "Visual Studio 15 2017" -A %PLATFORM% -D "BUILD_SHARED_LIBS=OFF" -D "PYILMBASE_ENABLE=0" -D "OPENEXR_VIEWERS_ENABLE=0" -D "ZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11" -D "ZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11/build/Release/zlibstatic.lib" ../
  - if "%PLATFORM%" == "x86"
    cmake -G "Visual Studio 15 2017" -D "BUILD_SHARED_LIBS=OFF" -D "PYILMBASE_ENABLE=0" -D "OPENEXR_VIEWERS_ENABLE=0" -D "ZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11" -D "ZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11/build/Release/zlibstatic.lib" ../
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  
  - cd thirdparty/tbb
  - mkdir build2
  - cd build2
  - if "%PLATFORM%" == "x64"
    cmake -G "Visual Studio 15 2017" -A %PLATFORM% ../
  - if "%PLATFORM%" == "x86"
    cmake -G "Visual Studio 15 2017" ../
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  
  - cd thirdparty/openvdb/openvdb-7.0.0
  - mkdir build
  - cd build
  - if "%PLATFORM%" == "x64"
    cmake -G "Visual Studio 15 2017" -A %PLATFORM% -D "OPENVDB_CORE_STATIC=OFF" -D "OPENVDB_BUILD_VDB_PRINT=OFF" -D "IlmBase_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/openexr/openexr-2.4.1" -D "IlmBase_Half_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/openexr/openexr-2.4.1/build/IlmBase/Half/Release/Half-2_4.lib" -D "TBB_INCLUDEDIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/tbb/include" -D "TBB_LIBRARYDIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/tbb/build2/Release" -D "ZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11" -D "ZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11/build/Release/zlibstatic.lib" -D "Blosc_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/blosc/c-blosc-1.18.1" -D "Blosc_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/blosc/c-blosc-1.18.1/build/blosc/Release/libblosc.lib" -D "BOOST_INCLUDEDIR=C:/Libraries/boost_1_66_0" -D "OPENVDB_DISABLE_BOOST_IMPLICIT_LINKING=ON" -D "CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=C:/Libraries/boost_1_66_0;%APPVEYOR_BUILD_FOLDER%/thirdparty/blosc/c-blosc-1.18.1/blosc;%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11/build" ../
  - if "%PLATFORM%" == "x86"
    cmake -G "Visual Studio 15 2017" -D "OPENVDB_CORE_STATIC=OFF" -D "OPENVDB_BUILD_VDB_PRINT=OFF" -D "IlmBase_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/openexr/openexr-2.4.1" -D "IlmBase_Half_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/openexr/openexr-2.4.1/build/IlmBase/Half/Release/Half-2_4.lib" -D "TBB_INCLUDEDIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/tbb/include" -D "TBB_LIBRARYDIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/tbb/build2/Release" -D "ZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11" -D "ZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11/build/Release/zlibstatic.lib" -D "Blosc_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/thirdparty/blosc/c-blosc-1.18.1" -D "Blosc_LIBRARY=%APPVEYOR_BUILD_FOLDER%/thirdparty/blosc/c-blosc-1.18.1/build/blosc/Release/libblosc.lib" -D "BOOST_INCLUDEDIR=C:/Libraries/boost_1_66_0" -D "OPENVDB_DISABLE_BOOST_IMPLICIT_LINKING=ON" -D "CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=C:/Libraries/boost_1_66_0;%APPVEYOR_BUILD_FOLDER%/thirdparty/blosc/c-blosc-1.18.1/blosc;%APPVEYOR_BUILD_FOLDER%/thirdparty/zlib/zlib-1.2.11/build" ../
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  
  - if not exist CGAL-5.1-beta1-Setup.exe
    appveyor DownloadFile https://github.com/CGAL/cgal/releases/download/releases/CGAL-5.1-beta1/CGAL-5.1-beta1-Setup.exe -FileName CGAL-5.1-beta1-Setup.exe
  - if "%PLATFORM%" == "x86"
    CGAL-5.1-beta1-Setup.exe /S /D=%APPVEYOR_BUILD_FOLDER%\CGAL-5.1-beta1

build: false

test_script:
  - set PATH=%PATH%;%QTDIR%\bin
  
  - if "%PLATFORM%" == "x64"
    qmake "BOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0" "CGAL_DIR=%APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-5.1-beta1"
  - if "%PLATFORM%" == "x86"
    qmake "BOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0" "CGAL_DIR=%APPVEYOR_BUILD_FOLDER%\CGAL-5.1-beta1"
  - nmake -f Makefile.Release
  - cd %APPVEYOR_BUILD_FOLDER%

after_test:
  # Check deps by Dependency Walker
  - set /p VCRedistVersion=<"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt"
  - set VCREDIST_CRT_DIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%VCRedistVersion%\%PLATFORM%\Microsoft.VC141.CRT

  - set TAG=%APPVEYOR_REPO_TAG_NAME%
  - if "%TAG%" == ""
    set TAG=unstable
  - if "%PLATFORM%" == "x64"
    set RELEASE_FILENAME=autoremesher-%TAG%.zip
  - if "%PLATFORM%" == "x86"
    set RELEASE_FILENAME=autoremesher-%TAG%-x86.zip
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\release\autoremesher.exe
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\tbb\build2\Release\tbb.dll
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\openvdb\openvdb-7.0.0\build\openvdb\Release\openvdb.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-5.1-beta1\auxiliary\gmp\lib\libgmp-10.dll
  - if "%PLATFORM%" == "x86"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\CGAL-5.1-beta1\auxiliary\gmp\lib\libgmp-10.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-5.1-beta1\auxiliary\gmp\lib\libmpfr-4.dll
  - if "%PLATFORM%" == "x86"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\CGAL-5.1-beta1\auxiliary\gmp\lib\libmpfr-4.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win64\bin\libcrypto-1_1-x64.dll
  - if "%PLATFORM%" == "x86"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win32\bin\libcrypto-1_1.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win64\bin\libssl-1_1-x64.dll
  - if "%PLATFORM%" == "x86"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win32\bin\libssl-1_1.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Widgets.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Gui.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Core.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Network.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5WinExtras.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\opengl32sw.dll
  - 7z a %RELEASE_FILENAME% "%VCREDIST_CRT_DIR%\msvcp140.dll"
  - 7z a %RELEASE_FILENAME% "%VCREDIST_CRT_DIR%\vcruntime140.dll"
  - mkdir platforms
  - copy %QTDIR%\plugins\platforms\qwindows.dll %APPVEYOR_BUILD_FOLDER%\platforms\qwindows.dll
  - 7z a %RELEASE_FILENAME% -r %APPVEYOR_BUILD_FOLDER%\platforms\
  - mkdir imageformats
  - copy %QTDIR%\plugins\imageformats\qjpeg.dll %APPVEYOR_BUILD_FOLDER%\imageformats\qjpeg.dll
  - 7z a %RELEASE_FILENAME% -r %APPVEYOR_BUILD_FOLDER%\imageformats\

artifacts:
  - path: '*.zip'
    name: platform_zips

deploy:
  - provider: GitHub
    release: $(TAG)
    force_update: true
    auth_token:
      secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
    artifact: platform_zips
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: GitHub
    release: $(TAG)
    force_update: true
    auth_token:
      secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
    artifact: platform_zips
    draft: false
    prerelease: false
    on:
      branch: ci

  - provider: GitHub
    release: $(TAG)
    force_update: true
    auth_token:
      secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
    artifact: platform_zips
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true
