names = { #XXX use property utility names instead
    'allow_selection': 'Allow Selection',
    'alt_scroll_shape_type': 'Allow Alt Scroll Shape',
    'apply_scale': 'Apply Scale',
    'apply_slices': 'Apply Slices',
    'array_around_cursor': 'Array Around 3D Cursor',
    'array_axis': 'Array Axis',
    'array_count': 'Array Count',
    'array_distance': 'Array Distance',
    'array_circle': 'Array Circle',
    'auto_depth': 'Auto Depth',
    'auto_depth_large': 'Large Depth',
    'auto_depth_custom_proportions': 'Custom Proportions',
    'auto_depth_multiplier': 'Depth Multiplier',
    'auto_ortho': 'Auto Ortho',
    'auto_smooth': 'Auto Smooth',
    'axis': 'Cursor Axis',
    'bbox': 'Bbox',
    'bevel_segments': 'Bevel Segments',
    'bevel_width': 'Bevel Width',
    'bevel_front_face': 'Bevel Front Face',
    'boolean_solver': 'Boolean Solver',
    'bounds': 'Show Bounds',
    'circle_diameter': 'Diameter',
    'circle_vertices': 'Circle Vertices',
    'collection': 'Collection Color',
    'cursor': 'Cursor',
    'cut': 'Cut',
    'cycle_all': 'Cycle All Cutters',
    'd_helper': 'Helper Instead Of Pie On D Key',
    'destructive_menu': 'Destructive Menu',
    'dimension_x': 'X',
    'dimension_y': 'Y',
    'dimension_z': 'Z',
    'dot': 'Dot',
    'dot_vert': 'Verts',
    'dot_bevel': 'Bevel Dot',
    'dot_highlight': 'Dot Highlight',
    'dots': 'Display Dot Gizmos',
    'draw_line': 'Draw Line',
    'draw_line_angle': 'Line Angle',
    'edit_disable_modifiers': 'Disable Ctrl & Shift LMB (Edit Mode)',
    'enable_surface_toggle': 'Enable Surface Toggle',
    'extract': 'Extract',
    'grid': 'Grid',
    'grid_gizmo': 'Grid Gizmo',
    'grid_mode': 'Grid Mode Color',
    'grid_wire': 'Grid Wire',
    'hops_mark': 'HOps Mark',
    'inset': 'Inset',
    'inset_slice': 'Inset Slice',
    'inset_thickness': 'Inset Thickness',
    'intersect': 'Intersect',
    'join': 'Join',
    'join_flip_z': 'Join Flip Z',
    'keep_modifiers': 'Keep Modifiers',
    'knife': 'Knife',
    'lazorcut_depth': 'Depth',
    'lazorcut_limit': 'Lazorcut Limit',
    'accucut': 'Accucut',
    'make': 'Make',
    'make_active': 'Shift to Active',
    'make_align_z': 'Make on Z',
    'mirror_axis': 'Mirror Axis',
    'mirror_bisect_axis': 'Bisect Axis',
    'mirror_flip_axis': 'Bisect Axis',
    'mode_label': 'Mode Label',
    'negative': 'Negative',
    'ngon_angle': 'Ngon Snap Angle',
    'ngon_last_line_threshold': 'Last Threshold',
    'ngon_previous_edge': 'Previous Edge',
    'offset': 'Offset',
    'operation_label': 'Operation Label',
    'orient_active_edge': 'Use active edge for orienting',
    'orient_method': 'Orient Method',
    'ortho_view_align': 'View Align in Ortho',
    'override_headers': 'Replace Headers',
    'parent_shape': 'Parent Shape',
    'persistent_taper': 'Persistent Taper',
    'quad_bevel': 'Quad Bevel',
    'quick_execute': 'Quick Execute',
    'recut': 'Recut',
    'reduce_opacity_editmode': 'Reduce Opacity in Edit',
    'release_lock_repeat': 'Repeat Lock',
    'repeat_single_click': 'Repeat Click',
    'repeat_threshold': 'Repeat Threshold',
    'rotate_angle': 'Rotate Snap Angle',
    'rotate_axis': 'Rotate Axis',
    'scroll_adjust_circle': 'Scroll Adjust Circle',
    'set_origin': 'Set Origin',
    'shape_label': 'Shape Label',
    'shift_operation': 'Shift Operation',
    'shift_operation_enable': 'Enable Shift Operation',
    'shift_operation_preset': 'Preset',
    'show_shape': 'Show Shape',
    'show_shape_wire': 'Show Shape Wire',
    'show_wire': 'Show Wire',
    'simple_topbar': 'Simple Topbar',
    'simple_helper': 'Simple Helper',
    'simple_trace': 'Simple Trace',
    'slice': 'Slice',
    'snap': 'Snap',
    'snap_point': 'Snap point',
    'snap_point_highlight': 'Highlight',
    'snap_label': 'Snap Label',
    'solidify_thickness': 'Solidify Thickness',
    'solidify_offset': 'Solidify Offset',
    'sort_modifiers': 'Sort Modifiers',
    'stipple_width': 'Stipple Width',
    'straight_edges': 'Straight Corner Flow',
    'surface_label': 'Surface Label',
    'tab': 'Tab',
    'taper': 'Taper',
    'thick_wire': 'Thick Wire',
    'transform_gizmo': 'Transform Gizmo',
    'wedge': 'Wedge',
    'wire': 'Wire',
    'wire_use_mode': 'Use Mode',
    'wire_only': 'Wires Only',
    'wire_width': 'Wire Width',
    'extract_fade': 'Extract Fade',
    'cycle_dimensions': 'Recall Dimensions',
    'auto_flip_xy': 'Auto Flip Draw'}

